"""次回面談時間を追加

Revision ID: 7f82a5dadb32
Revises: 0710edfedebb
Create Date: 2026-09-05 05:27:23.382478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f82a5dadb32'
down_revision = '0710edfedebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_meeting_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('next_meeting_time')

    # ### end Alembic commands ###
